import type { QueueState } from './upload-client'
import { momentsDir, type MomentsLang } from './couple-headline'

export type { MomentsLang }
export { momentsDir, readMomentsLanguage, saveMomentsLanguage } from './couple-headline'

export const GUEST_LANGUAGE_OPTIONS: { id: MomentsLang; label: string }[] = [
  { id: 'ar', label: 'العربية' },
  { id: 'he', label: 'עברית' },
  { id: 'en', label: 'English' },
]

const guestCopyAr = {
  language: 'اللغة',
  preparing: 'جاري التحضير…',
  shareTitle: 'شاركونا لحظاتكم 🤍',
  welcomeLine1: 'ساعدونا أن نرى هذه الليلة الجميلة من عيونكم',
  welcomeLine2: 'كل صورة، فيديو أو كلمة منكم ستبقى ذكرى جميلة معنا.',
  welcomeBack: 'أهلًا من جديد، {name} 🤍',
  readyAnother: 'جاهز تضيف لحظة ثانية؟',
  photo: 'صورة',
  video: 'فيديو',
  message: 'رسالة',
  addMoment: 'أضف لحظة جديدة',
  shareMoment: 'شارك لحظتك',
  sendCoupleMessage: 'أرسل رسالة للعروسين',
  viewMine: 'عرض مشاركاتي',
  notMe: 'هذا ليس أنا',
  helloName: 'أهلًا {name} 🤍',
  uploadPrompt: 'شو اللحظة اللي حابب تشاركنا إياها؟',
  takePhotoVideo: 'التقط صورة أو فيديو',
  chooseFromPhone: 'اختر من الهاتف',
  compressingPhoto: 'جاري تجهيز الصورة...',
  compressingVideo: 'جاري تجهيز الفيديو...',
  captionPlaceholder: 'كلمة صغيرة من القلب 🤍',
  sendMemory: 'إرسال الذكرى',
  retry: 'إعادة المحاولة',
  backHome: 'العودة للصفحة الرئيسية',
  memoryArrived: 'وصلتنا ذكراك 🤍',
  thanksForMoment: 'شكرًا لأنك شاركتنا لحظة من هذه الليلة',
  addAnotherMemory: 'أضف ذكرى أخرى',
  writeMessage: 'اكتب رسالة',
  myShares: 'ذكرياتي اللي شاركتها',
  statsLine: '{photos} صورة  ·  {videos} فيديو  ·  {messages} رسالة',
  noMemoriesYet: 'لم تشارك أي ذكرى بعد 🤍',
  storyTapToView: 'اضغط الصورة أو الفيديو للمشاهدة',
  captionOnMemory: 'كلمة على هذه الذكرى',
  captionEditPlaceholder: 'اختياري — اكتب كلمة صغيرة من القلب',
  editCaption: 'عدّل الكلمة',
  addCaption: 'أضف كلمة على هذه الذكرى',
  deleteThisMemory: 'حذف هذه الذكرى',
  leaveWord: 'اترك كلمة من القلب 🤍',
  onBehalfOf: 'باسم {name}',
  sendMessage: 'إرسال الرسالة',
  messageArrived: 'وصلت رسالتك للعروسين 🤍',
  sendMoreAnytime: 'يمكنك إرسال المزيد في أي وقت خلال الحفل',
  sharePhotoOrVideo: 'شارك صورة أو فيديو',
  writeAnotherMessage: 'اكتب رسالة أخرى',
  closedTitle: 'شكرًا لأنكم كنتم جزءًا من فرحتنا 🤍',
  identifyTitle: 'قبل أن نبدأ 🤍',
  identifyBody: 'نحب أن نعرف ممن وصلتنا هذه الذكرى',
  yourName: 'اسمك',
  lastFour: 'آخر 4 أرقام من الهاتف',
  optional: 'اختياري',
  start: 'ابدأ',
  namePrivacy: 'سنحفظ اسمك على هذا الجهاز فقط لتجميع ذكرياتك معنا.',
  close: 'إغلاق',
  cancel: 'إلغاء',
  saveNameFailed: 'لم نتمكن من حفظ اسمك، حاول مرة أخرى',
  openFileFailed: 'تعذّر فتح الملف',
  chooseFileFirst: 'اختر صورة أو فيديو أولًا',
  someFilesUnsupported: 'بعض الملفات غير مدعومة أو أكبر من المسموح',
  someFilesFailed: 'بعض الملفات لم تُرسل، جرّب مرة أخرى',
  rateLimited: 'أرسلت الكثير خلال وقت قصير، انتظر قليلًا 🤍',
  uploadsClosed: 'انتهى وقت إضافة الذكريات',
  sendFailed: 'تعذّر الإرسال، تأكد من الاتصال وحاول مجددًا',
  messageFailed: 'لم تصل الرسالة، حاول مرة أخرى',
  confirmDeleteTitle: 'تأكيد الحذف',
  confirmDeleteBody: 'بدك تحذف هذه الذكرى؟ ما رح تقدر ترجعها بعد الحذف.',
  confirmSwitchTitle: 'تأكيد تبديل الضيف',
  confirmSwitchBody:
    'الجهاز مسجّل الآن باسم {name}. إذا اخترت "هذا ليس أنا" رح نفتح جلسة جديدة لشخص ثاني.',
  confirmDelete: 'نعم، احذف',
  confirmNotMe: 'نعم، هذا ليس أنا',
  guestFallback: 'ضيف',
  deleted: 'تم حذف الذكرى',
  deleteFailed: 'تعذّر الحذف، حاول مرة أخرى',
  loadingVideo: 'جاري تحميل الفيديو...',
  loading: 'جاري التحميل...',
  storyMoment: 'لحظتنا الآن',
  storyClose: 'إغلاق',
  storyMute: 'كتم الصوت',
  storyUnmute: 'تشغيل الصوت',
  queued: 'في الانتظار',
  compressing: 'جاري التجهيز...',
  uploading: 'جاري الرفع',
  uploadingVideo: 'جاري رفع الفيديو {progress}%',
  uploadingPhoto: 'جاري الرفع {progress}%',
  confirming: 'جارٍ تأكيد الحفظ...',
  saved: 'تم الحفظ 🤍',
  retrying: 'إعادة المحاولة',
  waitingConnection: 'بانتظار الاتصال...',
  statusFailed: 'فشل الرفع',
  pagination: 'الصفحات',
  pagePrev: 'السابق',
  pageNext: 'التالي',
  pageStatus: 'صفحة {current} من {total}',
  wantThisEvent: 'بدي أعمل نظام زي هاد لمناسبتي',
  leadTitle: 'خلّونا نجهّز مناسبتكم',
  leadBody: 'اتركوا اسمكم ورقمكم، منتواصل معكم.',
  leadName: 'الاسم',
  leadPhone: 'رقم الهاتف',
  leadNotes: 'رسالة اختيارية',
  leadSubmit: 'إرسال',
  leadThanksTitle: 'استلمنا تفاصيلك 🤍',
  leadThanksBody: 'رح نتواصل معك قريبًا',
  leadError: 'ما قدرنا نرسل التفاصيل، حاولوا مرة ثانية.',
  leadNameRequired: 'الاسم مطلوب.',
  leadPhoneRequired: 'رقم الهاتف غير واضح، حاولوا مرة ثانية.',
  copyright: 'جميع الحقوق محفوظة LaylaSoftware',
} as const

export type GuestCopy = Record<keyof typeof guestCopyAr, string>

const guestCopyHe: GuestCopy = {
  language: 'שפה',
  preparing: 'מתכוננים…',
  shareTitle: 'שתפו איתנו את הרגעים 🤍',
  welcomeLine1: 'עזרו לנו לראות את הלילה היפה הזה בעיניים שלכם',
  welcomeLine2: 'כל תמונה, סרטון או מילה מכם יישארו זיכרון יפה איתנו.',
  welcomeBack: 'שלום שוב, {name} 🤍',
  readyAnother: 'מוכנים להוסיף עוד רגע?',
  photo: 'תמונה',
  video: 'סרטון',
  message: 'הודעה',
  addMoment: 'הוסיפו רגע חדש',
  shareMoment: 'שתפו רגע',
  sendCoupleMessage: 'שלחו הודעה לזוג',
  viewMine: 'השיתופים שלי',
  notMe: 'זה לא אני',
  helloName: 'שלום {name} 🤍',
  uploadPrompt: 'איזה רגע בא לכם לשתף איתנו?',
  takePhotoVideo: 'צלמו תמונה או סרטון',
  chooseFromPhone: 'בחרו מהטלפון',
  compressingPhoto: 'מכינים את התמונה...',
  compressingVideo: 'מכינים את הסרטון...',
  captionPlaceholder: 'מילה קטנה מהלב 🤍',
  sendMemory: 'שליחת הזיכרון',
  retry: 'ניסיון חוזר',
  backHome: 'חזרה לעמוד הראשי',
  memoryArrived: 'הזיכרון שלכם הגיע אלינו 🤍',
  thanksForMoment: 'תודה ששיתפתם איתנו רגע מהלילה הזה',
  addAnotherMemory: 'הוסיפו עוד זיכרון',
  writeMessage: 'כתבו הודעה',
  myShares: 'השיתופים שלי',
  statsLine: '{photos} תמונות  ·  {videos} סרטונים  ·  {messages} הודעות',
  noMemoriesYet: 'עדיין לא שיתפתם זיכרון 🤍',
  storyTapToView: 'לחצו על התמונה או הסרטון לצפייה',
  captionOnMemory: 'מילה על הזיכרון הזה',
  captionEditPlaceholder: 'אופציונלי — כתבו מילה קטנה מהלב',
  editCaption: 'עריכת המילה',
  addCaption: 'הוסיפו מילה לזיכרון הזה',
  deleteThisMemory: 'מחיקת הזיכרון הזה',
  leaveWord: 'השאירו מילה מהלב 🤍',
  onBehalfOf: 'בשם {name}',
  sendMessage: 'שליחת ההודעה',
  messageArrived: 'ההודעה שלכם הגיעה לזוג 🤍',
  sendMoreAnytime: 'אפשר לשלוח עוד בכל רגע במהלך האירוע',
  sharePhotoOrVideo: 'שתפו תמונה או סרטון',
  writeAnotherMessage: 'כתבו הודעה נוספת',
  closedTitle: 'תודה שהייתם חלק מהשמחה שלנו 🤍',
  identifyTitle: 'לפני שמתחילים 🤍',
  identifyBody: 'נשמח לדעת ממי הגיע הזיכרון הזה',
  yourName: 'השם שלכם',
  lastFour: '4 הספרות האחרונות של הטלפון',
  optional: 'אופציונלי',
  start: 'התחלה',
  namePrivacy: 'נשמור את השם רק במכשיר הזה כדי לאסוף את הזיכרונות שלכם איתנו.',
  close: 'סגירה',
  cancel: 'ביטול',
  saveNameFailed: 'לא הצלחנו לשמור את השם, נסו שוב',
  openFileFailed: 'לא ניתן לפתוח את הקובץ',
  chooseFileFirst: 'בחרו קודם תמונה או סרטון',
  someFilesUnsupported: 'חלק מהקבצים אינם נתמכים או גדולים מהמותר',
  someFilesFailed: 'חלק מהקבצים לא נשלחו, נסו שוב',
  rateLimited: 'שלחתם יותר מדי בזמן קצר, המתינו קצת 🤍',
  uploadsClosed: 'זמן הוספת הזיכרונות הסתיים',
  sendFailed: 'השליחה נכשלה, בדקו את החיבור ונסו שוב',
  messageFailed: 'ההודעה לא הגיעה, נסו שוב',
  confirmDeleteTitle: 'אישור מחיקה',
  confirmDeleteBody: 'למחוק את הזיכרון הזה? לא ניתן לשחזר אותו אחרי המחיקה.',
  confirmSwitchTitle: 'אישור החלפת אורח',
  confirmSwitchBody: 'המכשיר רשום כעת על שם {name}. אם תבחרו "זה לא אני" נפתח סשן חדש למישהו אחר.',
  confirmDelete: 'כן, מחקו',
  confirmNotMe: 'כן, זה לא אני',
  guestFallback: 'אורח',
  deleted: 'הזיכרון נמחק',
  deleteFailed: 'המחיקה נכשלה, נסו שוב',
  loadingVideo: 'טוענים את הסרטון...',
  loading: 'טוענים...',
  storyMoment: 'הרגע שלנו',
  storyClose: 'סגירה',
  storyMute: 'השתק',
  storyUnmute: 'בטל השתקה',
  queued: 'ממתין',
  compressing: 'מכינים...',
  uploading: 'מעלים',
  uploadingVideo: 'מעלים את הסרטון {progress}%',
  uploadingPhoto: 'מעלים {progress}%',
  confirming: 'מאשרים שמירה...',
  saved: 'נשמר 🤍',
  retrying: 'ניסיון חוזר',
  waitingConnection: 'ממתין לחיבור...',
  statusFailed: 'ההעלאה נכשלה',
  pagination: 'עמודים',
  pagePrev: 'הקודם',
  pageNext: 'הבא',
  pageStatus: 'עמוד {current} מתוך {total}',
  wantThisEvent: 'אני רוצה מערכת כזאת לאירוע שלי',
  leadTitle: 'בואו נכין את האירוע שלכם',
  leadBody: 'השאירו שם ומספר, ונחזור אליכם.',
  leadName: 'שם',
  leadPhone: 'טלפון',
  leadNotes: 'הודעה אופציונלית',
  leadSubmit: 'שליחה',
  leadThanksTitle: 'קיבלנו את הפרטים 🤍',
  leadThanksBody: 'נחזור אליכם בקרוב',
  leadError: 'לא הצלחנו לשלוח, נסו שוב.',
  leadNameRequired: 'יש להזין שם.',
  leadPhoneRequired: 'מספר הטלפון לא ברור, נסו שוב.',
  copyright: 'כל הזכויות שמורות LaylaSoftware',
}

const guestCopyEn: GuestCopy = {
  language: 'Language',
  preparing: 'Getting ready…',
  shareTitle: 'Share your moments with us 🤍',
  welcomeLine1: 'Help us see this beautiful night through your eyes',
  welcomeLine2: 'Every photo, video, or word from you will remain a lovely memory with us.',
  welcomeBack: 'Welcome back, {name} 🤍',
  readyAnother: 'Ready to add another moment?',
  photo: 'Photo',
  video: 'Video',
  message: 'Message',
  addMoment: 'Add a new moment',
  shareMoment: 'Share your moment',
  sendCoupleMessage: 'Send a message to the couple',
  viewMine: 'View my shares',
  notMe: 'This isn’t me',
  helloName: 'Hello {name} 🤍',
  uploadPrompt: 'What moment would you like to share with us?',
  takePhotoVideo: 'Take a photo or video',
  chooseFromPhone: 'Choose from your phone',
  compressingPhoto: 'Preparing the photo...',
  compressingVideo: 'Preparing the video...',
  captionPlaceholder: 'A small word from the heart 🤍',
  sendMemory: 'Send the memory',
  retry: 'Try again',
  backHome: 'Back to the home page',
  memoryArrived: 'We received your memory 🤍',
  thanksForMoment: 'Thank you for sharing a moment from this night',
  addAnotherMemory: 'Add another memory',
  writeMessage: 'Write a message',
  myShares: 'Memories I shared',
  statsLine: '{photos} photos  ·  {videos} videos  ·  {messages} messages',
  noMemoriesYet: 'You haven’t shared a memory yet 🤍',
  storyTapToView: 'Tap a photo or video to view',
  captionOnMemory: 'A word on this memory',
  captionEditPlaceholder: 'Optional — a small word from the heart',
  editCaption: 'Edit the note',
  addCaption: 'Add a word to this memory',
  deleteThisMemory: 'Delete this memory',
  leaveWord: 'Leave a word from the heart 🤍',
  onBehalfOf: 'From {name}',
  sendMessage: 'Send the message',
  messageArrived: 'Your message reached the couple 🤍',
  sendMoreAnytime: 'You can send more at any time during the celebration',
  sharePhotoOrVideo: 'Share a photo or video',
  writeAnotherMessage: 'Write another message',
  closedTitle: 'Thank you for being part of our joy 🤍',
  identifyTitle: 'Before we begin 🤍',
  identifyBody: 'We’d love to know who this memory came from',
  yourName: 'Your name',
  lastFour: 'Last 4 digits of your phone',
  optional: 'optional',
  start: 'Start',
  namePrivacy: 'We’ll save your name on this device only, to gather your memories with us.',
  close: 'Close',
  cancel: 'Cancel',
  saveNameFailed: 'We couldn’t save your name, please try again',
  openFileFailed: 'Couldn’t open the file',
  chooseFileFirst: 'Choose a photo or video first',
  someFilesUnsupported: 'Some files are unsupported or larger than allowed',
  someFilesFailed: 'Some files were not sent, please try again',
  rateLimited: 'You sent a lot in a short time, please wait a moment 🤍',
  uploadsClosed: 'The time to add memories has ended',
  sendFailed: 'Couldn’t send, check your connection and try again',
  messageFailed: 'The message didn’t go through, please try again',
  confirmDeleteTitle: 'Confirm delete',
  confirmDeleteBody: 'Delete this memory? You won’t be able to get it back.',
  confirmSwitchTitle: 'Confirm guest switch',
  confirmSwitchBody: 'This device is registered as {name}. If you choose “This isn’t me”, we’ll open a new session for someone else.',
  confirmDelete: 'Yes, delete',
  confirmNotMe: 'Yes, this isn’t me',
  guestFallback: 'Guest',
  deleted: 'Memory deleted',
  deleteFailed: 'Couldn’t delete, please try again',
  loadingVideo: 'Loading video...',
  loading: 'Loading...',
  storyMoment: 'Our Moment',
  storyClose: 'Close',
  storyMute: 'Mute',
  storyUnmute: 'Unmute',
  queued: 'Waiting',
  compressing: 'Preparing...',
  uploading: 'Uploading',
  uploadingVideo: 'Uploading video {progress}%',
  uploadingPhoto: 'Uploading {progress}%',
  confirming: 'Confirming save...',
  saved: 'Saved 🤍',
  retrying: 'Trying again',
  waitingConnection: 'Waiting for connection...',
  statusFailed: 'Upload failed',
  pagination: 'Pages',
  pagePrev: 'Previous',
  pageNext: 'Next',
  pageStatus: 'Page {current} of {total}',
  wantThisEvent: 'I want a system like this for my event',
  leadTitle: 'Let’s set up your event',
  leadBody: 'Leave your name and number, and we’ll be in touch.',
  leadName: 'Name',
  leadPhone: 'Phone',
  leadNotes: 'Optional message',
  leadSubmit: 'Send',
  leadThanksTitle: 'We received your details 🤍',
  leadThanksBody: 'We’ll be in touch soon',
  leadError: 'We couldn’t send this. Please try again.',
  leadNameRequired: 'Name is required.',
  leadPhoneRequired: 'That phone number doesn’t look right.',
  copyright: 'All rights reserved LaylaSoftware',
}

const translations: Record<MomentsLang, GuestCopy> = {
  ar: guestCopyAr,
  he: guestCopyHe,
  en: guestCopyEn,
}

export function getGuestCopy(lang: MomentsLang): GuestCopy {
  return translations[lang] ?? guestCopyAr
}

export function fillCopy(template: string, vars: Record<string, string | number> = {}) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => {
    const value = vars[key]
    return value == null ? '' : String(value)
  })
}

export function queueStatusLabel(
  copy: GuestCopy,
  item: { state: QueueState; progress: number; mediaType: 'photo' | 'video' },
) {
  if (item.state === 'uploading') {
    return fillCopy(item.mediaType === 'video' ? copy.uploadingVideo : copy.uploadingPhoto, {
      progress: item.progress,
    })
  }
  if ((item.state === 'compressing' || item.state === 'authorizing') && item.mediaType === 'video') {
    return copy.compressingVideo
  }
  if (item.state === 'queued') return copy.queued
  if (item.state === 'compressing' || item.state === 'authorizing') return copy.compressing
  if (item.state === 'confirming') return copy.confirming
  if (item.state === 'completed') return copy.saved
  if (item.state === 'retrying') return copy.retrying
  if (item.state === 'waiting_connection') return copy.waitingConnection
  if (item.state === 'failed') return copy.statusFailed
  return copy.compressing
}

const HE_FONT_ID = 'guest-font-he'

export function ensureGuestFont(lang: MomentsLang) {
  if (typeof document === 'undefined' || lang !== 'he') return
  if (document.getElementById(HE_FONT_ID)) return
  const link = document.createElement('link')
  link.id = HE_FONT_ID
  link.rel = 'stylesheet'
  link.href = 'https://fonts.googleapis.com/css2?family=Noto+Sans+Hebrew:wght@400;500&display=swap'
  document.head.appendChild(link)
}

export function applyGuestDocumentLang(lang: MomentsLang) {
  if (typeof document === 'undefined') return
  document.documentElement.lang = lang
  document.documentElement.dir = momentsDir(lang)
  ensureGuestFont(lang)
}
